#!/usr/bin/env python3
"""Choose which boards measure bot strength, and split them for tuning.

With both seats played on every board, a board tells two bots apart only when
one of them wins both games of a seat-swapped pair. A board on which the seat
decides (Union wins both, or Xenon wins both) adds no information, however
lopsided it is. This script plays two cheap pairings on every board with
`nectaris-sim match --per-board`, keeps boards whose share of decisive pairs
averages at least --min-info, and splits the kept boards by position in the
sorted list: 2 of 4 tuning, 1 of 4 validation, 1 of 4 final test.

  python3 tools/sim/board-survey.py [--cycles=8] [--min-info=0.3]

Writes sim/data/board-sets.json, which `nectaris-sim match --boards=set:NAME`
and tools/sim/tune-weights.py read. Rerun only when the boards or the engine
rules change; the split is deterministic given the survey.
"""
import argparse, json, re, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BIN = ROOT / "sim/target/release/nectaris-sim"
PAIRINGS = [
    ("tactical", "classic", "survey1"),
    ("greedy:u.advance=1.5,u.danger=0.4,x.advance=0.6", "tactical", "survey2"),
]

a = argparse.ArgumentParser()
a.add_argument("--cycles", type=int, default=8)
a.add_argument("--min-info", type=float, default=0.3)
args = a.parse_args()

def survey(spec_a, spec_b, seed):
    out = subprocess.run([BIN, "match", f"--a={spec_a}", f"--b={spec_b}", "--boards=all", f"--cycles={args.cycles}",
                          f"--seed={seed}", "--per-board"], capture_output=True, text=True)
    if out.returncode:
        sys.exit(out.stderr)
    rows = {}
    for line in out.stdout.splitlines()[2:]:
        p = line.split()
        board = int(p[0])
        pairs, a_sweeps, b_sweeps, union_both, xenon_both = map(int, p[2:7])
        rows[board] = dict(name=p[1], info=(a_sweeps + b_sweeps) / pairs, union=union_both / pairs, xenon=xenon_both / pairs)
    return rows

runs = [survey(*p) for p in PAIRINGS]
boards = sorted(runs[0])
info = {b: sum(r[b]["info"] for r in runs) / len(runs) for b in boards}
keep = [b for b in boards if info[b] >= args.min_info]
sets = {"train": [], "validation": [], "test": []}
for i, b in enumerate(keep):
    sets[["train", "train", "validation", "test"][i % 4]].append(b)
result = {
    "note": "Generated by tools/sim/board-survey.py; see BOTS.md. Boards where the seat decides most pairs are excluded.",
    "cycles": args.cycles, "min_info": args.min_info, "pairings": [[p[0], p[1], p[2]] for p in PAIRINGS],
    "excluded": [b for b in boards if b not in keep],
    "info": {str(b): round(info[b], 3) for b in boards},
    "sets": sets,
}
path = ROOT / "sim/data/board-sets.json"
path.write_text(json.dumps(result, indent=1) + "\n")
print({k: len(v) for k, v in sets.items()}, "excluded", len(result["excluded"]), "->", path)
