/* Nectaris remake — official Hudson normal campaign.
 *
 * Generated from Hudson's official 1997 Windows freeware port with:
 *   node tools/extract-original-campaign.js path/to/Nec.exe > js/data-maps.js
 * Terrain, buildings, deployments and factory inventories reproduce the
 * Windows remake's built-in campaign. English unit IDs follow the
 * TurboGrafx-16 release.
 */
"use strict";

var CAMPAIGN = [
  { name: "REVOLT", blurb: "The original opening battle: infantry and Bisons contest a bridge between two prison camps.",
    turnLimit: 50,
    grid: [
      "MMMMMMwvMMMwwMM",
      "M..M..wwv.hhhh.",
      "M..M.h..vv..h--",
      "M.hhM..M.v.--.M",
      "MMh.MMM..=-...M",
      "M....h..-v....M",
      "M....M.--MMM.B.",
      "MMMMM--wM..M.w.",
      "M.Bw-...M.h.MMM",
      "M..........wwMM",
    ],
    buildings: [
      {"col":13,"row":6,"owner":1},
      {"col":2,"row":8,"owner":0},
    ],
    units: [
      {"t":"CHARLIE","o":0,"x":6,"y":7},
      {"t":"CHARLIE","o":0,"x":2,"y":9},
      {"t":"BISON","o":0,"x":4,"y":8},
      {"t":"BISON","o":0,"x":5,"y":8},
      {"t":"BISON","o":0,"x":7,"y":4},
      {"t":"CHARLIE","o":1,"x":10,"y":2},
      {"t":"CHARLIE","o":1,"x":10,"y":5},
      {"t":"BISON","o":1,"x":11,"y":5},
      {"t":"BISON","o":1,"x":12,"y":4},
    ] },

  { name: "ICARUS", blurb: "A larger infantry-and-Bison engagement across broken lunar terrain.",
    turnLimit: 50,
    grid: [
      "MMM------------",
      "M--hhMhhhMhww..",
      "-hhhMMMMMMMMB.-",
      "-.h..MMMMMMhh--",
      "-...whhhh..--hM",
      "--..hhh----hh.M",
      ".-..h--wwMhMh..",
      ".B.--..wwMMMMM.",
      "....hMhhwhM.M..",
      "wwwwwMMMhh...ww",
    ],
    buildings: [
      {"col":12,"row":2,"owner":1},
      {"col":1,"row":7,"owner":0},
    ],
    units: [
      {"t":"CHARLIE","o":0,"x":2,"y":8},
      {"t":"CHARLIE","o":0,"x":2,"y":5},
      {"t":"CHARLIE","o":0,"x":3,"y":6},
      {"t":"BISON","o":0,"x":2,"y":3},
      {"t":"BISON","o":0,"x":5,"y":6},
      {"t":"BISON","o":0,"x":6,"y":5},
      {"t":"BISON","o":0,"x":8,"y":5},
      {"t":"BISON","o":0,"x":7,"y":8},
      {"t":"CHARLIE","o":1,"x":10,"y":2},
      {"t":"CHARLIE","o":1,"x":12,"y":4},
      {"t":"CHARLIE","o":1,"x":14,"y":3},
      {"t":"BISON","o":1,"x":11,"y":4},
      {"t":"BISON","o":1,"x":12,"y":3},
      {"t":"BISON","o":1,"x":13,"y":6},
    ] },

  { name: "CYRANO", blurb: "Xenon begins with a factory containing Kilroy infantry and Hadrian artillery.",
    turnLimit: 50,
    grid: [
      "v---whM..-..-..",
      "vv..--.----w-B.",
      ".v.www-wwwhw-..",
      ".MMMwwwwhhww---",
      "MB..M..Mh..---F",
      "M..wMMMMM--..-h",
      "hhwwMMMM.-....-",
      "--wwM.MMM-....-",
      ".M--..M..-.h..-",
      "MMMM--------.--",
    ],
    buildings: [
      {"col":13,"row":1,"owner":1},
      {"col":1,"row":4,"owner":0},
      {"col":14,"row":4,"owner":1,"stored":["KILROY","HADRIAN"]},
    ],
    units: [
      {"t":"CHARLIE","o":0,"x":1,"y":5},
      {"t":"CHARLIE","o":0,"x":2,"y":4},
      {"t":"BISON","o":0,"x":6,"y":4},
      {"t":"BISON","o":0,"x":4,"y":8},
      {"t":"BISON","o":0,"x":6,"y":9},
      {"t":"BISON","o":0,"x":9,"y":8},
      {"t":"BISON","o":1,"x":9,"y":5},
      {"t":"BISON","o":1,"x":11,"y":7},
      {"t":"BISON","o":1,"x":14,"y":5},
      {"t":"CHARLIE","o":1,"x":9,"y":1},
    ] },

  { name: "RAMSEY", blurb: "Aircraft, artillery and four factories widen the battle across a tall battlefield.",
    turnLimit: 50,
    grid: [
      "MMM...M.wB..hhv",
      "MMM.wwM.......v",
      "MMMww..M.w..vv.",
      "M..ww.MMMMwF.vw",
      "M.ww..MMMMMw.vw",
      "M.ww.MMMMM.www.",
      "MM.wMF.wMM.Mwww",
      "MMMwMM..MMMMM.w",
      "MM.w.M..MMMMM..",
      "M.Fwww...MM....",
      ".hhhwww.M......",
      "h.hhw...MMM....",
      ".wh....M.h.....",
      ".wF..MMhhh.....",
      "Mwww.MMhhhhw...",
      ".ww..h.-wwww.MM",
      "M..B.--.--wwwMM",
      "M...w..w..-ww.M",
      "M..w.hhww.-.w..",
      "MM...hhhhh----.",
    ],
    buildings: [
      {"col":9,"row":0,"owner":1},
      {"col":11,"row":3,"owner":1,"stored":["BISON","HADRIAN"]},
      {"col":5,"row":6,"owner":-1,"stored":["SEEKER"]},
      {"col":2,"row":9,"owner":-1,"stored":["BISON"]},
      {"col":2,"row":13,"owner":0,"stored":["GRIZZLY"]},
      {"col":3,"row":16,"owner":0},
    ],
    units: [
      {"t":"GRIZZLY","o":0,"x":7,"y":11},
      {"t":"POLAR","o":0,"x":10,"y":15},
      {"t":"BISON","o":0,"x":5,"y":12},
      {"t":"HADRIAN","o":0,"x":7,"y":15},
      {"t":"SEEKER","o":0,"x":4,"y":14},
      {"t":"CHARLIE","o":0,"x":3,"y":11},
      {"t":"KILROY","o":0,"x":5,"y":11},
      {"t":"KILROY","o":0,"x":8,"y":14},
      {"t":"EAGLE","o":1,"x":10,"y":6},
      {"t":"BISON","o":1,"x":7,"y":1},
      {"t":"BISON","o":1,"x":13,"y":8},
      {"t":"SLAGGER","o":1,"x":14,"y":7},
      {"t":"CHARLIE","o":1,"x":10,"y":5},
      {"t":"KILROY","o":1,"x":9,"y":2},
    ] },

  { name: "NEWTON", blurb: "Four neutral factories hold the weapons that decide this mobile engagement.",
    turnLimit: 50,
    grid: [
      "....M.M...wwwvv",
      "wMB.......vvv.M",
      "wwhh.......v..M",
      "whhhhhhh....F.M",
      "h...hhhh.....MM",
      ".....hhh....MMM",
      ".M....hhh...MMM",
      "MMMM....h...MMM",
      "MMM..M.hh..hwwM",
      "M..ww.h..hhwwww",
      "wwwwF..-hhwwwww",
      "wwww..-.--hhhww",
      ".M.......---F.h",
      "MMMM....-....hh",
      "MMMM..w--w.w.ww",
      "M.M....-..wwwwM",
      ".F...--.-..wwwM",
      "...--...-...wwM",
      "---.....--..www",
      ".....ww...-B..w",
    ],
    buildings: [
      {"col":2,"row":1,"owner":0},
      {"col":12,"row":3,"owner":-1,"stored":["LENET","HAWKEYE"]},
      {"col":4,"row":10,"owner":-1,"stored":["POLAR","SEEKER"]},
      {"col":12,"row":12,"owner":-1,"stored":["HUNTER","SLAGGER","LYNX"]},
      {"col":1,"row":16,"owner":-1,"stored":["TITAN"]},
      {"col":11,"row":19,"owner":1},
    ],
    units: [
      {"t":"GRIZZLY","o":0,"x":10,"y":8},
      {"t":"BISON","o":0,"x":4,"y":5},
      {"t":"RABBIT","o":0,"x":6,"y":9},
      {"t":"RABBIT","o":0,"x":11,"y":4},
      {"t":"CHARLIE","o":0,"x":2,"y":6},
      {"t":"CHARLIE","o":0,"x":7,"y":1},
      {"t":"BISON","o":1,"x":4,"y":16},
      {"t":"LENET","o":1,"x":10,"y":13},
      {"t":"RABBIT","o":1,"x":8,"y":15},
      {"t":"CHARLIE","o":1,"x":6,"y":17},
      {"t":"KILROY","o":1,"x":12,"y":14},
    ] },

  { name: "SENECA", blurb: "Air power and troop carriers enter a race for three neutral factories.",
    turnLimit: 50,
    grid: [
      "wwwwwww-.-.MM.w",
      "MM.----.-.-...w",
      "M.-.wMh.F.--F.w",
      "M.-wwMMMMMh-..w",
      "M.-ww.MMMMM.-.w",
      ".--wMMMM..F.--.",
      ".-wwMMMM.hhhh-.",
      ".-.wwMMMhhhh.-.",
      ".-.MwMMMhMhhh-.",
      ".-.MMMMMMMMM.-.",
      "ww-wMMMMMMMMM-.",
      "ww-ww...MMMM..-",
      "ww-wwM.MMMMMMw-",
      "MM-B.MMMMMMM.w-",
      "M.--wMM..MMwww-",
      "w..-MMwvMMMww.-",
      "w--hMM.wv.M.B.-",
      "w-.hMMMwvvMMM.-",
      "-.hMMM.wwv.v..-",
      ".hMMMMMwwwv.v..",
    ],
    buildings: [
      {"col":8,"row":2,"owner":-1,"stored":["EAGLE","GRIZZLY","SEEKER"]},
      {"col":12,"row":2,"owner":-1,"stored":["LYNX"]},
      {"col":10,"row":5,"owner":-1,"stored":["OCTOPUS","SEEKER","GIANT"]},
      {"col":3,"row":13,"owner":0},
      {"col":12,"row":16,"owner":1},
    ],
    units: [
      {"t":"FALCON","o":0,"x":4,"y":11},
      {"t":"EAGLE","o":0,"x":2,"y":17},
      {"t":"POLAR","o":0,"x":4,"y":3},
      {"t":"BISON","o":0,"x":1,"y":14},
      {"t":"HADRIAN","o":0,"x":0,"y":8},
      {"t":"RABBIT","o":0,"x":1,"y":2},
      {"t":"CHARLIE","o":0,"x":2,"y":8},
      {"t":"CHARLIE","o":0,"x":0,"y":11},
      {"t":"MULE","o":0,"x":1,"y":5},
      {"t":"MULE","o":0,"x":1,"y":9},
      {"t":"HUNTER","o":1,"x":12,"y":18},
      {"t":"TITAN","o":1,"x":13,"y":11},
      {"t":"RABBIT","o":1,"x":14,"y":7},
      {"t":"HAWKEYE","o":1,"x":12,"y":15},
      {"t":"CHARLIE","o":1,"x":13,"y":17},
      {"t":"KILROY","o":1,"x":14,"y":11},
      {"t":"MULE","o":1,"x":14,"y":15},
    ] },

  { name: "SABINE", blurb: "Both armies begin with factory reserves while two neutral arsenals divide the front.",
    turnLimit: 50,
    grid: [
      "wwwwwMM.wwMMMM..-..--..hhhhhhh",
      "www.....wwwwMMM.-.-..hhhh.hhh.",
      "........wwwwM-.----..whww....B",
      "..F.....M.ww-w-.-v--.wwwww....",
      ".--..M......-w.F..v-.wwww....-",
      "-....MMwwh..-vw..Mv-..w.....-.",
      "..B..wwMwhhh-.vMMMv-........F.",
      "ww.wwwwMMhww-Mv-M-.-....MM....",
      "wMwwwwww.Mhh--=M-.----..M.....",
      "MMMMMMwMw.h.-.vvF.-..-...MMM..",
    ],
    buildings: [
      {"col":29,"row":2,"owner":1},
      {"col":2,"row":3,"owner":0,"stored":["TRIGGER","TRIGGER","GIANT"]},
      {"col":15,"row":4,"owner":-1,"stored":["EAGLE","BISON","OCTOPUS","LYNX"]},
      {"col":2,"row":6,"owner":0},
      {"col":28,"row":6,"owner":1,"stored":["MULE","CHARLIE","MULE","TRIGGER","RABBIT","HAWKEYE"]},
      {"col":16,"row":9,"owner":-1,"stored":["BISON","SLAGGER","SEEKER"]},
    ],
    units: [
      {"t":"GRIZZLY","o":0,"x":5,"y":2},
      {"t":"BISON","o":0,"x":10,"y":5},
      {"t":"HADRIAN","o":0,"x":9,"y":3},
      {"t":"CHARLIE","o":0,"x":4,"y":5},
      {"t":"CHARLIE","o":0,"x":7,"y":2},
      {"t":"MULE","o":0,"x":1,"y":2},
      {"t":"MULE","o":0,"x":3,"y":3},
      {"t":"POLAR","o":1,"x":25,"y":8},
      {"t":"BISON","o":1,"x":21,"y":7},
      {"t":"BISON","o":1,"x":25,"y":5},
      {"t":"OCTOPUS","o":1,"x":23,"y":3},
      {"t":"KILROY","o":1,"x":27,"y":7},
    ] },

  { name: "ARATUS", blurb: "A broad east-west battlefield filled with aircraft, carriers and factory reserves.",
    turnLimit: 50,
    grid: [
      "wwwwMMMMMMMMM.ww.MMMM.MMMww...",
      ".B.wMMMMMMM.F.wM.MMMMM...ww-B.",
      ".-..wwMMMMMM.M.MMMM..wwF.--...",
      "hh--.wwww.MMMM.....-.-h..-.h.h",
      "hh..--www-..M..-.--.-.---h..h.",
      "hhh..-.--.--.--.-.MM....vvhh.v",
      "h.h...-M.MMM-M.M.MM.ww..hvhhww",
      "wF.h.h.MMMMMMMMMMM.ww...Mv.hvv",
      "ww.hh..MMMM.MMM.MMMwwMwwwwvhh.",
      "wwhMMMMMM.wwww.wMw.wwMMMwwvh.-",
    ],
    buildings: [
      {"col":1,"row":1,"owner":0},
      {"col":12,"row":1,"owner":-1,"stored":["GRIZZLY","POLAR","RABBIT","HAWKEYE","EAGLE","SLAGGER","TITAN","PELICAN"]},
      {"col":28,"row":1,"owner":1},
      {"col":23,"row":2,"owner":1,"stored":["PELICAN","ATLAS","BISON","EAGLE","MULE","TRIGGER","SEEKER","CHARLIE"]},
      {"col":1,"row":7,"owner":0,"stored":["FALCON","PELICAN","ATLAS","GRIZZLY","BISON","MULE","TRIGGER","EAGLE","CHARLIE"]},
    ],
    units: [
      {"t":"FALCON","o":0,"x":6,"y":3},
      {"t":"EAGLE","o":0,"x":3,"y":4},
      {"t":"BISON","o":0,"x":10,"y":5},
      {"t":"HADRIAN","o":0,"x":5,"y":8},
      {"t":"SEEKER","o":0,"x":6,"y":5},
      {"t":"SEEKER","o":0,"x":9,"y":3},
      {"t":"HAWKEYE","o":0,"x":8,"y":6},
      {"t":"CHARLIE","o":0,"x":4,"y":6},
      {"t":"PANTHER","o":0,"x":2,"y":3},
      {"t":"PELICAN","o":0,"x":2,"y":7},
      {"t":"FALCON","o":1,"x":19,"y":6},
      {"t":"HUNTER","o":1,"x":16,"y":3},
      {"t":"HUNTER","o":1,"x":22,"y":1},
      {"t":"BISON","o":1,"x":17,"y":5},
      {"t":"TITAN","o":1,"x":19,"y":4},
      {"t":"HADRIAN","o":1,"x":21,"y":7},
      {"t":"SEEKER","o":1,"x":20,"y":3},
      {"t":"HAWKEYE","o":1,"x":18,"y":3},
      {"t":"CHARLIE","o":1,"x":27,"y":4},
      {"t":"PANTHER","o":1,"x":28,"y":2},
      {"t":"PELICAN","o":1,"x":26,"y":3},
    ] },

  { name: "GALOIS", blurb: "A large combined-arms battle with four neutral arsenals and extensive reserves.",
    turnLimit: 50,
    grid: [
      "hhh...-.wwMMMMMvvwwMMMMMM.MMMM",
      "hhh----.wwMMM.vh.MMMM....wM.MM",
      "hh.-...wwwMMMvvMMMM..F.wwwwww.",
      "h..F..wwwwMMwwvMM......wwwwww.",
      "h..-..wwww.MMMvMM...hhh.www...",
      "h.-...wwM.MMMwwMMM.hhhhh......",
      "..--...ww.MMMwwMM...hhhhhw....",
      ".B..-..w..MMMMw......hhhww....",
      "....--....MMM.F.vvMM.wwwMww..-",
      ".wwww-ww.....M...vMMMwwww...-.",
      "wwwMw-ww...M....w.MM.wwMMM.--.",
      "w.wMMM-ww..MMM....M..ww.MMM-..",
      "ww.MM.-..M..MMMF......www.w-..",
      "ww...w-.M.MM.....MM.....www-..",
      "MM.Fww-.MwMM.MMMMMMM.....-.-..",
      "M.....-.w..MMMMMMMM.....-.-.-.",
      "MM...--.ww.MM.MvMM.v.......--.",
      "M..--...ww.MMwhvMM..v....-.F..",
      "M..-...wwwMMwvwMMMMwvv.--.-...",
      "MM.-.w.wwwMMwwvMMM.wwv-.B....M",
    ],
    buildings: [
      {"col":21,"row":2,"owner":-1,"stored":["HUNTER","PELICAN","CHARLIE"]},
      {"col":3,"row":3,"owner":0,"stored":["MULE","KILROY","FALCON","EAGLE","POLAR"]},
      {"col":1,"row":7,"owner":0},
      {"col":14,"row":8,"owner":-1,"stored":["FALCON","BISON","BISON","LENET","MULE","TRIGGER","PELICAN"]},
      {"col":15,"row":12,"owner":-1,"stored":["SLAGGER","TITAN","HADRIAN","RABBIT","HAWKEYE","MULE","TRIGGER"]},
      {"col":3,"row":14,"owner":-1,"stored":["FALCON","EAGLE","POLAR","RABBIT","LYNX","HAWKEYE","PELICAN","ATLAS"]},
      {"col":27,"row":17,"owner":1,"stored":["LYNX","MULE","ATLAS","OCTOPUS","SLAGGER","FALCON"]},
      {"col":24,"row":19,"owner":1},
    ],
    units: [
      {"t":"GRIZZLY","o":0,"x":9,"y":9},
      {"t":"POLAR","o":0,"x":6,"y":10},
      {"t":"BISON","o":0,"x":5,"y":7},
      {"t":"HADRIAN","o":0,"x":6,"y":7},
      {"t":"RABBIT","o":0,"x":3,"y":8},
      {"t":"SEEKER","o":0,"x":9,"y":7},
      {"t":"HAWKEYE","o":0,"x":7,"y":8},
      {"t":"CHARLIE","o":0,"x":6,"y":6},
      {"t":"HUNTER","o":1,"x":28,"y":19},
      {"t":"SLAGGER","o":1,"x":24,"y":18},
      {"t":"TITAN","o":1,"x":19,"y":11},
      {"t":"LENET","o":1,"x":23,"y":14},
      {"t":"OCTOPUS","o":1,"x":23,"y":16},
      {"t":"RABBIT","o":1,"x":25,"y":14},
      {"t":"SEEKER","o":1,"x":20,"y":15},
      {"t":"HAWKEYE","o":1,"x":21,"y":16},
      {"t":"PANTHER","o":1,"x":27,"y":13},
      {"t":"CHARLIE","o":1,"x":21,"y":13},
    ] },

  { name: "DARWIN", blurb: "Seven factories spread aircraft and heavy weapons across a deep battlefield.",
    turnLimit: 50,
    grid: [
      "hhh.h..MM.M.MMwwh.hh.MMMM.MMM.",
      "h.Fw----.---M---.......---M...",
      "hw-wwB.M-..w-w.w----.--.vv-.F.",
      "ww--...MMM.wwwwhwwww-wwwwv--..",
      "w.-.--.MM.w.hhh.hhhhFwwww.v---",
      "hh--MM--.---.---.---.hhhw-v-.-",
      "hhh-Mwww-.M--h.M-MMM--M--.-Mw-",
      "hh.-MMw.ww.-MMMMMMMMM--.ww..-w",
      "h--wMMMMwww-MMM.MMMMMM--www.-w",
      ".-wwMMM.w.w-.wwwM.hMM..-www.--",
      "M-wwM......-wFwwwwwwM..-wMMM.-",
      ".-...M...--Mw.wwwFw...-..MM..-",
      "h-.wMMMM.-.MMMMM...MMM-F.MM..-",
      "h-wwwhM..-.MMMMMMMMMM.-..MM--h",
      "h-wwwh.ww-..MMMMMMMMM.-M...-.h",
      "hw-hhhFww-.wwMMMM....--MMM.-..",
      "..-.hM..-h--wwM.ww.---.MM..-B.",
      ".--------.hhwh.hhh..ww-h..M-..",
      ".-M-.-.-h-h-h-h-h-.-w---h--..M",
      "w.-.-.-.-.-.-.-.-.-.-.-.-....M",
    ],
    buildings: [
      {"col":2,"row":1,"owner":0,"stored":["FALCON","EAGLE","GRIZZLY","PANTHER","MULE"]},
      {"col":5,"row":2,"owner":0},
      {"col":28,"row":2,"owner":-1,"stored":["HUNTER","HADRIAN","OCTOPUS","PELICAN","TRIGGER","RABBIT","HAWKEYE"]},
      {"col":20,"row":4,"owner":-1,"stored":["OCTOPUS","PELICAN","ATLAS","MULE","KILROY"]},
      {"col":13,"row":10,"owner":-1,"stored":["TRIGGER","EAGLE","PELICAN","OCTOPUS"]},
      {"col":17,"row":11,"owner":-1,"stored":["HUNTER","HAWKEYE","PELICAN","CHARLIE"]},
      {"col":23,"row":12,"owner":1,"stored":["HUNTER","HAWKEYE","PANTHER","MULE"]},
      {"col":6,"row":15,"owner":-1,"stored":["EAGLE","HADRIAN","RABBIT","LYNX","HAWKEYE","PELICAN","ATLAS","CHARLIE"]},
      {"col":28,"row":16,"owner":1},
    ],
    units: [
      {"t":"FALCON","o":0,"x":5,"y":6},
      {"t":"FALCON","o":0,"x":8,"y":2},
      {"t":"EAGLE","o":0,"x":10,"y":7},
      {"t":"BISON","o":0,"x":3,"y":4},
      {"t":"HADRIAN","o":0,"x":8,"y":6},
      {"t":"RABBIT","o":0,"x":10,"y":5},
      {"t":"SEEKER","o":0,"x":6,"y":5},
      {"t":"HAWKEYE","o":0,"x":3,"y":7},
      {"t":"HAWKEYE","o":0,"x":6,"y":1},
      {"t":"CHARLIE","o":0,"x":4,"y":3},
      {"t":"PANTHER","o":0,"x":10,"y":3},
      {"t":"HUNTER","o":1,"x":19,"y":15},
      {"t":"HUNTER","o":1,"x":24,"y":14},
      {"t":"SLAGGER","o":1,"x":22,"y":16},
      {"t":"LENET","o":1,"x":27,"y":12},
      {"t":"OCTOPUS","o":1,"x":26,"y":16},
      {"t":"SEEKER","o":1,"x":22,"y":12},
      {"t":"CHARLIE","o":1,"x":29,"y":17},
      {"t":"PANTHER","o":1,"x":27,"y":14},
    ] },

  { name: "PASCAL", blurb: "Six factories and large reserves make control of deployment routes decisive.",
    turnLimit: 50,
    grid: [
      "MMMMMMMMMMMMMMMMMMMMMM..v.vMvM",
      "MM.h.MMMM.MMMMM...MMMMM.MMv..M",
      "MMwwhhMw.wMMMw..F.wMMM..MMMMMM",
      "MMwwhh.MwwMMww...wMMMMM.MMMMMM",
      ".MMF...MMMMM.wB..wMMMM.MMMM..M",
      "v.MM...hMMMMM.-..wM.MMMMM.hh.M",
      "vvMM...hMMMMMM--..wMMMM..hhhww",
      ".v.MM..hhh.MMMMh-.hhMh.hhhwFww",
      "..v.MM....hhM..h-hhhhhhwhv.-..",
      "MMvv.vv...hhhhhh-whwhww...v-ww",
      "M.hhv.........wwwwwwwww..-=www",
      "M....h..........w...w....-vvwv",
      "MMMwwwhh.....h.h.........-.v.v",
      "M.wwwhwhhh...hhh.....MMM.-..vh",
      "M.wwhhh.h...hhhh.hh.MMMww-..v.",
      "...-........hMhhhhhhMMM.-...F.",
      "MM-.--....hhMMMMhhhhM..---.--M",
      "M.F...--hhhh.MMM.hhh...-..-F.M",
      "M..M.B..--h..MMwMMhh.--......M",
      "M.........--.MM.M..--w.h.....M",
    ],
    buildings: [
      {"col":16,"row":2,"owner":1,"stored":["TITAN","PELICAN","CHARLIE","GIANT","HUNTER","PELICAN","CHARLIE","RABBIT"]},
      {"col":3,"row":4,"owner":-1,"stored":["POLAR","LENET","OCTOPUS","SLAGGER","HADRIAN","HAWKEYE"]},
      {"col":14,"row":4,"owner":1},
      {"col":27,"row":7,"owner":-1,"stored":["TITAN","HUNTER","BISON","SLAGGER","MULE","ATLAS","PANTHER","TRIGGER"]},
      {"col":28,"row":15,"owner":-1,"stored":["SEEKER","BISON","LYNX","MULE","ATLAS"]},
      {"col":2,"row":17,"owner":0,"stored":["FALCON","PELICAN","CHARLIE","EAGLE","BISON","RABBIT"]},
      {"col":27,"row":17,"owner":-1,"stored":["EAGLE","RABBIT","RABBIT","MULE","KILROY"]},
      {"col":5,"row":18,"owner":0},
    ],
    units: [
      {"t":"FALCON","o":0,"x":12,"y":16},
      {"t":"BISON","o":0,"x":10,"y":14},
      {"t":"BISON","o":0,"x":2,"y":11},
      {"t":"SEEKER","o":0,"x":4,"y":12},
      {"t":"HAWKEYE","o":0,"x":7,"y":13},
      {"t":"CHARLIE","o":0,"x":5,"y":17},
      {"t":"PELICAN","o":0,"x":8,"y":19},
      {"t":"RABBIT","o":0,"x":12,"y":13},
      {"t":"HUNTER","o":1,"x":16,"y":5},
      {"t":"BISON","o":1,"x":12,"y":10},
      {"t":"SLAGGER","o":1,"x":13,"y":5},
      {"t":"RABBIT","o":1,"x":26,"y":8},
      {"t":"SEEKER","o":1,"x":13,"y":8},
      {"t":"SEEKER","o":1,"x":25,"y":11},
      {"t":"HAWKEYE","o":1,"x":16,"y":9},
      {"t":"CHARLIE","o":1,"x":14,"y":2},
    ] },

  { name: "HALLEY", blurb: "Three neutral arsenals anchor a dense combined-arms confrontation.",
    turnLimit: 50,
    grid: [
      "MMw-----vv....wwwwwwwMM.MMMMM.",
      "M.-....B.v.---.h.hw---....M..-",
      "..-..MM-..v-h-.hhh-...--h--F.-",
      "h.FwwMw-.-=hhh--h.-w.M.--.w..-",
      "hh.hww..-whhhh..---MMMM-wwww-.",
      "M.hhhhwwwhh..M..-.wMMM.-.Mw.-.",
      "MM..hhhhhhh.MMMM-hw.MM.-.MM.--",
      "M.hhhwhwh.hhMMM.-..MMM.-.MMM.-",
      "MMh..Mwww.h.MMM.-.MMMM.-.MM..-",
      "MMM.MMMMwMMMMMM.-.MMMMM-MMM.h-",
      "MM.wMMMMMMMMM...-h..M..-MMMM.-",
      "MM..MMMMMMM-.-..-..F..-.MMMMM-",
      "MMMM.MMMM.-.-.---..-..-.M....-",
      "MMM...M...-...--...-----.---..",
      "M........--.....-..-.Mh.-ww-B.",
      ".--------.......---hhhhhhhw-.w",
      ".-..............-.Mhhhhhh-h.-w",
      "hhF..w.....hhh..--h-h-h--.----",
      "hh..www.hh.hhh...h-.-w-.F.--.-",
      "hhh.www.hhhhhhh..hhhwww.....-.",
    ],
    buildings: [
      {"col":7,"row":1,"owner":0},
      {"col":27,"row":2,"owner":-1,"stored":["EAGLE","GRIZZLY","SEEKER","HUNTER","HAWKEYE"]},
      {"col":2,"row":3,"owner":0,"stored":["FALCON","EAGLE","BISON","HAWKEYE","PELICAN","CHARLIE","PANTHER"]},
      {"col":19,"row":11,"owner":-1,"stored":["HUNTER","HUNTER","HUNTER","TITAN","RABBIT","SEEKER","HAWKEYE","PELICAN","CHARLIE","PANTHER"]},
      {"col":28,"row":14,"owner":1},
      {"col":2,"row":17,"owner":-1,"stored":["FALCON","EAGLE","BISON","RABBIT","SEEKER","HAWKEYE","PELICAN","CHARLIE"]},
      {"col":24,"row":18,"owner":1,"stored":["HUNTER","PELICAN","CHARLIE","PANTHER"]},
    ],
    units: [
      {"t":"FALCON","o":0,"x":4,"y":2},
      {"t":"FALCON","o":0,"x":6,"y":4},
      {"t":"EAGLE","o":0,"x":9,"y":2},
      {"t":"BISON","o":0,"x":5,"y":0},
      {"t":"RABBIT","o":0,"x":14,"y":4},
      {"t":"LYNX","o":0,"x":14,"y":2},
      {"t":"SEEKER","o":0,"x":11,"y":1},
      {"t":"HAWKEYE","o":0,"x":7,"y":0},
      {"t":"HAWKEYE","o":0,"x":10,"y":0},
      {"t":"PANTHER","o":0,"x":8,"y":4},
      {"t":"HUNTER","o":1,"x":22,"y":18},
      {"t":"HUNTER","o":1,"x":26,"y":14},
      {"t":"SLAGGER","o":1,"x":18,"y":10},
      {"t":"TITAN","o":1,"x":27,"y":16},
      {"t":"RABBIT","o":1,"x":20,"y":11},
      {"t":"RABBIT","o":1,"x":28,"y":10},
      {"t":"LYNX","o":1,"x":23,"y":13},
      {"t":"SEEKER","o":1,"x":18,"y":14},
      {"t":"SEEKER","o":1,"x":25,"y":12},
      {"t":"HAWKEYE","o":1,"x":21,"y":12},
      {"t":"HAWKEYE","o":1,"x":29,"y":12},
    ] },

  { name: "BORMAN", blurb: "Both armies begin entirely inside factories and must choose their opening deployments.",
    turnLimit: 50,
    grid: [
      "MMMMMMMMM.hMMMM.MMMMMMM.MMMMMM",
      "MMM...M.hhhhM..wM..MM....w.MMM",
      "MMM.B...h.hh.wh.w.ww....www..M",
      "MMMM...wwwh...ww...www..w....M",
      "MMM..F.www....ww.....M..F....M",
      "M.ww....ww....vv...MM..M...wMM",
      "MMww.M......w..v...M...MM.h.MM",
      "M.w.MMMMw..h.h..v...M....ww..M",
      "M...MMMM..hhMhMMvMwwM....wwMMM",
      "MM..MM.MM...hhMMMMww......wMMM",
      "MMhMMMMM.M..hhMMM.wwhh..w..MM.",
      "MMMMMMMMMMMM..vv.Fwwh.ww......",
      "MMMMMMM.MMM....v..ww..wwww....",
      "MMM....wM..MMM..hhhwww.Mw.....",
      "MM..ww..w.MMMM..h..wwwMMMMww..",
      "Mww.wwh...MMMw......wwMMM.wwB.",
      "M.w.w.M...M..ww..w.M.....www..",
      "MM........MMMMwwww......www..w",
      "M..F...wwwwwM..wwh.www....F..w",
      "M.w...wwwMwwww.wwhhwwwww...Mww",
    ],
    buildings: [
      {"col":4,"row":2,"owner":0},
      {"col":5,"row":4,"owner":0,"stored":["OCTOPUS","MULE","ATLAS","PANTHER","GRIZZLY","LYNX","BISON","MULE","TRIGGER","CHARLIE","CHARLIE"]},
      {"col":24,"row":4,"owner":-1,"stored":["SLAGGER","TITAN","HADRIAN","OCTOPUS","MULE","ATLAS","CHARLIE"]},
      {"col":17,"row":11,"owner":-1,"stored":["BISON","OCTOPUS","BISON","CHARLIE","LENET","ATLAS","CHARLIE"]},
      {"col":28,"row":15,"owner":1},
      {"col":3,"row":18,"owner":-1,"stored":["POLAR","BISON","GIANT","HADRIAN","OCTOPUS","LYNX","MULE","ATLAS","CHARLIE"]},
      {"col":26,"row":18,"owner":1,"stored":["PANTHER","CHARLIE","SLAGGER","RABBIT","GIANT","MULE","ATLAS","KILROY","OCTOPUS","MULE","TRIGGER"]},
    ],
    units: [
    ] },

  { name: "APPOLO", blurb: "Artillery, aircraft and heavy armour converge around six factories.",
    turnLimit: 50,
    grid: [
      "wwh.......w.......wwwww.hhh.hh",
      "ww.MMMMM.MMM.MF..........M..hh",
      "wwMMMMM.MMMMMMMMMMMMMM.MMMMM..",
      "w.......M.M..MMMMMMMMMMMM.MMM.",
      "..B..w........M...MMMM.MMMMM..",
      ".M.MMM.M.MMMMM....MMMMM.MMM...",
      "MMMMMMMMMMMMMMMM.h..MM.w...F..",
      "MMM.MMMMMMMMMMMMMM..MMMM.....h",
      "M.hh.MMMMMM....MMM...MM.......",
      "M.hh..MMM...F...MMMM.MM.hh.MMM",
      "MMMM.MMM.w.....MM..M....hF.MMM",
      "MMMMMMMM.wwMMM.MMMM........MMM",
      "MMMMMMMMMww.MMMMMMM..MMM.wMMM.",
      "MM.MMMM..F....M.M...MMM...MM..",
      "M...M............h..MMM...MMMh",
      ".........M.MMMMM....MMMM.....h",
      "...MMM.MMMMMMMMMM.MMMMM...hhh.",
      "...MMMMMMMMMM.M...MMM.....hh.w",
      "--.MMMMMM.........M...B.....ww",
      "..--MMM..whhF..h...w.w...wwwww",
    ],
    buildings: [
      {"col":14,"row":1,"owner":-1,"stored":["EAGLE"]},
      {"col":2,"row":4,"owner":0},
      {"col":27,"row":6,"owner":0,"stored":["CHARLIE","HADRIAN","BISON","HAWKEYE","GRIZZLY"]},
      {"col":12,"row":9,"owner":1,"stored":["CHARLIE","RABBIT","ATLAS","ATLAS","SLAGGER","SLAGGER"]},
      {"col":25,"row":10,"owner":-1,"stored":["ATLAS","BISON","BISON","MULE"]},
      {"col":9,"row":13,"owner":-1,"stored":["TITAN","LYNX","HAWKEYE","MULE","TRIGGER"]},
      {"col":22,"row":18,"owner":1},
      {"col":12,"row":19,"owner":-1,"stored":["HUNTER","TITAN","GIANT","HADRIAN","OCTOPUS","RABBIT","MULE","ATLAS","PANTHER"]},
    ],
    units: [
      {"t":"GRIZZLY","o":0,"x":8,"y":5},
      {"t":"BISON","o":0,"x":10,"y":4},
      {"t":"GIANT","o":0,"x":7,"y":4},
      {"t":"HADRIAN","o":0,"x":6,"y":4},
      {"t":"RABBIT","o":0,"x":2,"y":1},
      {"t":"LYNX","o":0,"x":9,"y":0},
      {"t":"CHARLIE","o":0,"x":7,"y":2},
      {"t":"PANTHER","o":0,"x":4,"y":3},
      {"t":"SLAGGER","o":1,"x":19,"y":18},
      {"t":"TITAN","o":1,"x":26,"y":18},
      {"t":"LENET","o":1,"x":28,"y":17},
      {"t":"RABBIT","o":1,"x":16,"y":19},
      {"t":"LYNX","o":1,"x":24,"y":16},
      {"t":"CHARLIE","o":1,"x":21,"y":17},
      {"t":"KILROY","o":1,"x":24,"y":19},
      {"t":"SEEKER","o":1,"x":14,"y":18},
    ] },

  { name: "KAISER", blurb: "Five factories distribute a large late-campaign force across the lunar front.",
    turnLimit: 50,
    grid: [
      ".MM-wvMMMM.M...-wwwww..v.MvvMM",
      "MMwFwwvMM..MM--M....w..B.MMMMM",
      "M..-w.vMMF.hM-.MMM.......vMMMM",
      "MM..--.......-wwMM.....w..vMMM",
      "MMMw.-..hhw..-w.MMM...wwvvvvMM",
      "MM.ww.--h..M.-.MMM..MMwwvhvv..",
      "Mwwww.ww--.MMM-MMMMMMMwwwwhw.-",
      "M.w.w.wMw-.MM.-MMMMM.M.wwww--v",
      "--h..MMMMM--..--MMMMM..Mwww-..",
      "..-.MMMMMMMM--.-.MM..---...-hh",
      ".w-.h.MMMMMMM-.-...--...---hhh",
      "ww-...M..MMM.-.F.--...hhhhhhhh",
      "w---...-.MM.-.--..MMhhhhh.h.hh",
      "w-..Fw-.--.--...--M.hhhhhhF.hh",
      "w-.......M-.h.MM..----..hh.hhh",
      ".-.....MMMMM..MMM.-...--hhhhhh",
      "MM--..M.MMMMMMM...-..M..--h.h.",
      "MM..--M.MMM..MM..--MMMMM.-..h.",
      "MMMB.-....M.M..h.-.MMMMMM.--.-",
      "MM...-.ww.MMM.hh.-.MM.M.....-.",
    ],
    buildings: [
      {"col":3,"row":1,"owner":-1,"stored":["FALCON","EAGLE","GRIZZLY","POLAR","BISON","HADRIAN","RABBIT","LYNX","HAWKEYE","OCTOPUS","MULE"]},
      {"col":23,"row":1,"owner":1},
      {"col":9,"row":2,"owner":-1,"stored":["GRIZZLY","OCTOPUS","MULE","ATLAS","RABBIT"]},
      {"col":15,"row":11,"owner":1,"stored":["TITAN","HUNTER","RABBIT","SEEKER","OCTOPUS","CHARLIE"]},
      {"col":4,"row":13,"owner":0,"stored":["GRIZZLY","PELICAN","LYNX","HADRIAN","POLAR"]},
      {"col":26,"row":13,"owner":-1,"stored":["HUNTER","PELICAN","CHARLIE","PELICAN","CHARLIE","FALCON","HUNTER","BISON","SLAGGER","TITAN","HADRIAN"]},
      {"col":3,"row":18,"owner":0},
    ],
    units: [
      {"t":"GRIZZLY","o":0,"x":4,"y":16},
      {"t":"BISON","o":0,"x":6,"y":14},
      {"t":"RABBIT","o":0,"x":8,"y":14},
      {"t":"SEEKER","o":0,"x":6,"y":12},
      {"t":"HAWKEYE","o":0,"x":4,"y":12},
      {"t":"CHARLIE","o":0,"x":2,"y":14},
      {"t":"CHARLIE","o":0,"x":5,"y":17},
      {"t":"TITAN","o":1,"x":12,"y":14},
      {"t":"BISON","o":1,"x":11,"y":12},
      {"t":"RABBIT","o":1,"x":10,"y":13},
      {"t":"HAWKEYE","o":1,"x":13,"y":10},
      {"t":"BISON","o":1,"x":15,"y":12},
      {"t":"KILROY","o":1,"x":20,"y":2},
      {"t":"CHARLIE","o":1,"x":28,"y":5},
      {"t":"MULE","o":1,"x":18,"y":2},
      {"t":"SEEKER","o":1,"x":24,"y":3},
    ] },

  { name: "NECTOR", blurb: "The original normal campaign's final assault on the Xenon prison camp.",
    turnLimit: 50,
    grid: [
      "MM.wwMMMMM..hhh.hhh...MMM...M.",
      "MMMwwMMMMMMhhh.B.hhh.MMMMMww.-",
      "MM.wwMMMMM.hh-----hh.MMMM.w--.",
      "MMMww.MMMh.--hh-hh--.MM..ww-.M",
      "MM.wwwww.--.hhh-hhh.--.-w--MMM",
      "MMMFwww--..M..h-h....F-.-.MMMM",
      "M------w.MMMMM.-MMMMMM.ww.MMMM",
      "-.MM.www.MMMMMM-MMMMM.www.MMMM",
      "-.MM.wwwwwMMM..-.MM..wwwMMMMM.",
      "hhMMM.wwwwww.w.-ww...FwwMMMMM.",
      "h.MM.MMM.wwwwww-..MMMM..MMMMMh",
      ".hMMMMMMMM.ww--.--MMMMM-.MM...",
      "h...MMMMMMM--..MMMMMMMM-....hh",
      "..hhM.MMM..-.MMMMMMMM..-.hhhh.",
      "..hhh.M...h-.MMMM..h.--..hhh..",
      "....h...hh.-........-..hhh..h.",
      "......h.hhh-.h.hhh.h-..h......",
      "...........-...hh.h.-.........",
      ".......B...-........-....F....",
      "...........-...F....-.........",
    ],
    buildings: [
      {"col":15,"row":1,"owner":1},
      {"col":3,"row":5,"owner":-1,"stored":["SLAGGER","HUNTER","HUNTER","SEEKER","PELICAN","GIANT","FALCON","SEEKER","SLAGGER","HUNTER"]},
      {"col":21,"row":5,"owner":1,"stored":["RABBIT","TITAN","HADRIAN","CHARLIE"]},
      {"col":21,"row":9,"owner":-1,"stored":["EAGLE","HUNTER","LENET","RABBIT","LYNX","TRIGGER"]},
      {"col":7,"row":18,"owner":0},
      {"col":25,"row":18,"owner":0,"stored":["FALCON","PANTHER","MULE","ATLAS","LYNX","HAWKEYE","FALCON"]},
      {"col":15,"row":19,"owner":-1,"stored":["EAGLE","GRIZZLY","SEEKER","POLAR","BISON","HAWKEYE","PANTHER"]},
    ],
    units: [
      {"t":"BISON","o":0,"x":10,"y":18},
      {"t":"BISON","o":0,"x":16,"y":18},
      {"t":"GIANT","o":0,"x":4,"y":16},
      {"t":"HADRIAN","o":0,"x":7,"y":16},
      {"t":"RABBIT","o":0,"x":10,"y":15},
      {"t":"RABBIT","o":0,"x":12,"y":17},
      {"t":"SEEKER","o":0,"x":9,"y":13},
      {"t":"KILROY","o":0,"x":13,"y":15},
      {"t":"HUNTER","o":1,"x":17,"y":5},
      {"t":"SLAGGER","o":1,"x":12,"y":11},
      {"t":"TITAN","o":1,"x":13,"y":8},
      {"t":"TITAN","o":1,"x":16,"y":10},
      {"t":"GIANT","o":1,"x":15,"y":7},
      {"t":"HADRIAN","o":1,"x":8,"y":8},
      {"t":"OCTOPUS","o":1,"x":14,"y":6},
      {"t":"SEEKER","o":1,"x":10,"y":10},
      {"t":"SEEKER","o":1,"x":19,"y":4},
      {"t":"ATLAS","o":1,"x":17,"y":11},
      {"t":"ATLAS","o":1,"x":13,"y":5},
      {"t":"ATLAS","o":1,"x":14,"y":1},
      {"t":"ATLAS","o":1,"x":19,"y":5},
      {"t":"CHARLIE","o":1,"x":10,"y":2},
    ] }
];

if (typeof module !== "undefined") module.exports = CAMPAIGN;
