/* Nectaris remake — campaign levelset.
 *
 * 16 missions. The map layouts here are original designs for this project
 * (the original game's map data is not reproduced); the campaign follows the
 * same structure: escalating unit introduction, factory play, and a final
 * combined-arms map. Mission names reuse the classic one-word codename style.
 *
 * Terrain legend (see data-terrain.js):
 *   .  plains      -  road       w  wasteland   h  hills
 *   M  mountains   v  valley     =  bridge
 *   F  factory     B  base       (owners set in `buildings`)
 *
 * Schema (also the custom-level JSON schema used by the editor):
 * {
 *   name, blurb, turnLimit,
 *   grid: ["row strings"...],
 *   buildings: [{col,row,owner:0|1|-1,stored:["TYPEID",...]}],
 *   units: [{t:"TYPEID", o:0|1, x, y, str?, exp?}]
 * }
 */
"use strict";

var CAMPAIGN = [

  { name: "REVOLT", blurb: "First contact. Tanks and infantry only — learn movement, terrain and the attack calculator.",
    turnLimit: 30,
    grid: [
      "hh...www..hh",
      "h..........h",
      "B----------B",
      "............",
      "..hh....hh..",
      "....vv......",
      "...ww..w....",
      "hh........hh",
    ],
    buildings: [
      { col: 0, row: 2, owner: 0 },
      { col: 11, row: 2, owner: 1 },
    ],
    units: [
      { t: "BISON", o: 0, x: 1, y: 1 }, { t: "BISON", o: 0, x: 1, y: 3 },
      { t: "CHARLIE", o: 0, x: 2, y: 2 },
      { t: "BISON", o: 1, x: 10, y: 1 }, { t: "LENET", o: 1, x: 10, y: 3 },
      { t: "CHARLIE", o: 1, x: 9, y: 2 },
    ] },

  { name: "ICARUS", blurb: "A neutral factory sits on the road between the bases. Capture it with infantry and field its stored units.",
    turnLimit: 35,
    grid: [
      "hh.........hh",
      "h....www....h",
      ".............",
      "B-----F-----B",
      ".............",
      "..hh.....hh..",
      ".....vvv.....",
      "h...........h",
      "hh.........hh",
    ],
    buildings: [
      { col: 0, row: 3, owner: 0 },
      { col: 12, row: 3, owner: 1 },
      { col: 6, row: 3, owner: -1, stored: ["KILROY", "LYNX"] },
    ],
    units: [
      { t: "BISON", o: 0, x: 1, y: 2 }, { t: "BISON", o: 0, x: 1, y: 4 },
      { t: "CHARLIE", o: 0, x: 1, y: 3 }, { t: "LYNX", o: 0, x: 2, y: 3 },
      { t: "BISON", o: 1, x: 11, y: 2 }, { t: "LENET", o: 1, x: 11, y: 4 },
      { t: "CHARLIE", o: 1, x: 11, y: 3 }, { t: "LYNX", o: 1, x: 10, y: 3 },
    ] },

  { name: "CYRANO", blurb: "Artillery joins the fight. Hadrians strike from range and never take counterfire — but can't move and shoot.",
    turnLimit: 35,
    grid: [
      "ww..........ww",
      "......hh......",
      "..hh..hh..hh..",
      "B------------B",
      "......hh......",
      "..ww......ww..",
      "......hh......",
      "h............h",
      "ww..........ww",
    ],
    buildings: [
      { col: 0, row: 3, owner: 0 },
      { col: 13, row: 3, owner: 1 },
    ],
    units: [
      { t: "BISON", o: 0, x: 1, y: 2 }, { t: "BISON", o: 0, x: 1, y: 4 },
      { t: "HADRIAN", o: 0, x: 1, y: 3 }, { t: "CHARLIE", o: 0, x: 2, y: 3 },
      { t: "LENET", o: 0, x: 2, y: 5 },
      { t: "BISON", o: 1, x: 12, y: 2 }, { t: "GRIZZLY", o: 1, x: 12, y: 4 },
      { t: "HADRIAN", o: 1, x: 12, y: 3 }, { t: "CHARLIE", o: 1, x: 11, y: 3 },
      { t: "LENET", o: 1, x: 11, y: 5 },
    ] },

  { name: "RAMSEY", blurb: "A valley splits the front; only the bridge — or wings — cross it. First air units.",
    turnLimit: 35,
    grid: [
      "hh....vv....hh",
      "......vv......",
      "..ww..vv..ww..",
      "......vv......",
      "B-----==-----B",
      "......vv......",
      "..ww..vv..ww..",
      "......vv......",
      "F.....vv.....F",
      "hh....vv....hh",
    ],
    buildings: [
      { col: 0, row: 4, owner: 0 },
      { col: 13, row: 4, owner: 1 },
      { col: 0, row: 8, owner: 0, stored: ["FALCON"] },
      { col: 13, row: 8, owner: 1, stored: ["EAGLE"] },
    ],
    units: [
      { t: "BISON", o: 0, x: 1, y: 3 }, { t: "BISON", o: 0, x: 1, y: 5 },
      { t: "EAGLE", o: 0, x: 2, y: 4 }, { t: "CHARLIE", o: 0, x: 1, y: 4 },
      { t: "GRIZZLY", o: 1, x: 12, y: 3 }, { t: "LENET", o: 1, x: 12, y: 5 },
      { t: "FALCON", o: 1, x: 11, y: 4 }, { t: "CHARLIE", o: 1, x: 12, y: 4 },
      { t: "SEEKER", o: 1, x: 12, y: 6 },
    ] },

  { name: "NEWTON", blurb: "Anti-air school: Seekers and the ranged Hawkeye punish careless pilots. Two neutral factories hold AA stock.",
    turnLimit: 40,
    grid: [
      "wwwww.....wwwww",
      "www.........www",
      "...hh.....hh...",
      "...............",
      "B-----.-.-----B",
      "...www...www...",
      ".....F...F.....",
      "..hh.......hh..",
      "www.........www",
      "wwwww.....wwwww",
    ],
    buildings: [
      { col: 0, row: 4, owner: 0 },
      { col: 14, row: 4, owner: 1 },
      { col: 5, row: 6, owner: -1, stored: ["HAWKEYE"] },
      { col: 9, row: 6, owner: -1, stored: ["SEEKER"] },
    ],
    units: [
      { t: "BISON", o: 0, x: 1, y: 3 }, { t: "LENET", o: 0, x: 1, y: 5 },
      { t: "EAGLE", o: 0, x: 2, y: 4 }, { t: "FALCON", o: 0, x: 2, y: 3 },
      { t: "CHARLIE", o: 0, x: 1, y: 4 }, { t: "SEEKER", o: 0, x: 2, y: 5 },
      { t: "GRIZZLY", o: 1, x: 13, y: 3 }, { t: "LENET", o: 1, x: 13, y: 5 },
      { t: "EAGLE", o: 1, x: 12, y: 4 }, { t: "FALCON", o: 1, x: 12, y: 3 },
      { t: "CHARLIE", o: 1, x: 13, y: 4 }, { t: "HAWKEYE", o: 1, x: 13, y: 6 },
    ] },

  { name: "SENECA", blurb: "The enemy base hides inside a valley ring only aircraft can cross. Ferry infantry with the Pelican; your factory holds an Atlas.",
    turnLimit: 40,
    grid: [
      "...............",
      "..........vvvv.",
      "..........v.Bv.",
      "..........vvvv.",
      "......ww.......",
      "B---...........",
      ".F.............",
      ".hh......ww....",
      "...............",
      "...............",
    ],
    buildings: [
      { col: 0, row: 5, owner: 0 },
      { col: 12, row: 2, owner: 1 },
      { col: 1, row: 6, owner: 0, stored: ["ATLAS", "TRIGGER"] },
    ],
    units: [
      { t: "PELICAN", o: 0, x: 2, y: 5 }, { t: "MULE", o: 0, x: 2, y: 6 },
      { t: "BISON", o: 0, x: 3, y: 5 }, { t: "LENET", o: 0, x: 3, y: 6 },
      { t: "CHARLIE", o: 0, x: 1, y: 5 }, { t: "EAGLE", o: 0, x: 2, y: 4 },
      { t: "GRIZZLY", o: 1, x: 9, y: 4 }, { t: "BISON", o: 1, x: 9, y: 6 },
      { t: "FALCON", o: 1, x: 12, y: 1 }, { t: "HAWKEYE", o: 1, x: 11, y: 4 },
      { t: "CHARLIE", o: 1, x: 13, y: 5 }, { t: "KILROY", o: 1, x: 11, y: 2 },
    ] },

  { name: "SABINE", blurb: "Trigger mines plug both bridges. Blast through or grind them down — an 80-defense mine shrugs off small arms.",
    turnLimit: 40,
    grid: [
      "................",
      "..hh...vv...hh..",
      ".......vv.......",
      "B------==------B",
      ".......vv.......",
      ".......vv.......",
      "...----==----...",
      ".......vv.......",
      "..ww...vv...ww..",
      "................",
    ],
    buildings: [
      { col: 0, row: 3, owner: 0 },
      { col: 15, row: 3, owner: 1 },
    ],
    units: [
      { t: "BISON", o: 0, x: 1, y: 2 }, { t: "BISON", o: 0, x: 1, y: 4 },
      { t: "POLAR", o: 0, x: 2, y: 3 }, { t: "HADRIAN", o: 0, x: 2, y: 4 },
      { t: "CHARLIE", o: 0, x: 1, y: 3 }, { t: "EAGLE", o: 0, x: 2, y: 2 },
      { t: "RABBIT", o: 0, x: 3, y: 3 },
      { t: "TRIGGER", o: 1, x: 8, y: 3 }, { t: "TRIGGER", o: 1, x: 8, y: 6 },
      { t: "OCTOPUS", o: 1, x: 11, y: 3 }, { t: "GRIZZLY", o: 1, x: 10, y: 4 },
      { t: "LENET", o: 1, x: 10, y: 6 }, { t: "CHARLIE", o: 1, x: 14, y: 3 },
      { t: "HADRIAN", o: 1, x: 11, y: 6 },
    ] },

  { name: "ARATUS", blurb: "Mountain war. Only infantry climbs the peaks — and holds 40% cover up there. A high factory holds reinforcements.",
    turnLimit: 40,
    grid: [
      "MMMM....MMMM..",
      "MM........MM..",
      "..MM....MM....",
      "....hh........",
      "B---....---..B",
      "....MM.F..MM..",
      "..MM....MM....",
      "....hh....hh..",
      "MM........MM..",
      "MMMM....MMMM..",
      "..............",
    ],
    buildings: [
      { col: 0, row: 4, owner: 0 },
      { col: 13, row: 4, owner: 1 },
      { col: 7, row: 5, owner: -1, stored: ["KILROY"] },
    ],
    units: [
      { t: "CHARLIE", o: 0, x: 1, y: 3 }, { t: "KILROY", o: 0, x: 1, y: 5 },
      { t: "PANTHER", o: 0, x: 2, y: 4 }, { t: "LENET", o: 0, x: 2, y: 5 },
      { t: "CHARLIE", o: 1, x: 12, y: 3 }, { t: "KILROY", o: 1, x: 12, y: 5 },
      { t: "PANTHER", o: 1, x: 11, y: 4 }, { t: "GRIZZLY", o: 1, x: 12, y: 6 },
    ] },

  { name: "GALIOS", blurb: "Full armored clash on open ground. Four factories feed the front — keep yours, raid theirs.",
    turnLimit: 45,
    grid: [
      "hh....ww....hh..",
      "................",
      "..F..........F..",
      "................",
      "....hh....hh....",
      "B--------------B",
      "....hh....hh....",
      "................",
      "..F..........F..",
      "................",
      "hh....ww....hh..",
    ],
    buildings: [
      { col: 0, row: 5, owner: 0 },
      { col: 15, row: 5, owner: 1 },
      { col: 2, row: 2, owner: 0, stored: ["LENET"] },
      { col: 13, row: 2, owner: 1, stored: ["LENET"] },
      { col: 2, row: 8, owner: 0, stored: ["BISON"] },
      { col: 13, row: 8, owner: 1, stored: ["GRIZZLY"] },
    ],
    units: [
      { t: "BISON", o: 0, x: 1, y: 4 }, { t: "BISON", o: 0, x: 1, y: 6 },
      { t: "POLAR", o: 0, x: 2, y: 5 }, { t: "TITAN", o: 0, x: 2, y: 4 },
      { t: "SLAGGER", o: 0, x: 2, y: 6 }, { t: "HADRIAN", o: 0, x: 1, y: 5 },
      { t: "CHARLIE", o: 0, x: 3, y: 5 }, { t: "RABBIT", o: 0, x: 3, y: 4 },
      { t: "GRIZZLY", o: 1, x: 14, y: 4 }, { t: "GRIZZLY", o: 1, x: 14, y: 6 },
      { t: "POLAR", o: 1, x: 13, y: 5 }, { t: "TITAN", o: 1, x: 13, y: 4 },
      { t: "SLAGGER", o: 1, x: 13, y: 6 }, { t: "OCTOPUS", o: 1, x: 14, y: 5 },
      { t: "CHARLIE", o: 1, x: 12, y: 5 }, { t: "RABBIT", o: 1, x: 12, y: 4 },
    ] },

  { name: "DARWIN", blurb: "Twin bridges, one gorge. Whoever holds both crossings dictates the battle.",
    turnLimit: 45,
    grid: [
      ".......vv.......",
      "..hh...vv...hh..",
      "...----==----...",
      ".......vv.......",
      ".......vv.......",
      "B......vv......B",
      ".......vv.......",
      ".......vv.......",
      "...----==----...",
      "..ww...vv...ww..",
      ".......vv.......",
    ],
    buildings: [
      { col: 0, row: 5, owner: 0 },
      { col: 15, row: 5, owner: 1 },
    ],
    units: [
      { t: "BISON", o: 0, x: 1, y: 4 }, { t: "LENET", o: 0, x: 1, y: 6 },
      { t: "POLAR", o: 0, x: 2, y: 5 }, { t: "HADRIAN", o: 0, x: 2, y: 4 },
      { t: "CHARLIE", o: 0, x: 2, y: 6 }, { t: "EAGLE", o: 0, x: 3, y: 5 },
      { t: "RABBIT", o: 0, x: 3, y: 3 },
      { t: "GRIZZLY", o: 1, x: 14, y: 4 }, { t: "TITAN", o: 1, x: 14, y: 6 },
      { t: "OCTOPUS", o: 1, x: 13, y: 5 }, { t: "CHARLIE", o: 1, x: 13, y: 6 },
      { t: "FALCON", o: 1, x: 12, y: 5 }, { t: "SEEKER", o: 1, x: 13, y: 4 },
      { t: "LYNX", o: 1, x: 12, y: 3 },
    ] },

  { name: "PASCAL", blurb: "Five neutral factories, two armies of scouts. The side that captures faster fields the bigger army.",
    turnLimit: 45,
    grid: [
      "...............",
      "..F.......F....",
      ".....hh........",
      "B.....F.......B",
      "...............",
      ".....hh........",
      "..F.......F....",
      "...............",
      "....ww....ww...",
      "...............",
    ],
    buildings: [
      { col: 0, row: 3, owner: 0 },
      { col: 14, row: 3, owner: 1 },
      { col: 2, row: 1, owner: -1, stored: ["LYNX"] },
      { col: 10, row: 1, owner: -1, stored: ["BISON"] },
      { col: 6, row: 3, owner: -1, stored: ["KILROY", "HADRIAN"] },
      { col: 2, row: 6, owner: -1, stored: ["SEEKER"] },
      { col: 10, row: 6, owner: -1, stored: ["LENET"] },
    ],
    units: [
      { t: "CHARLIE", o: 0, x: 1, y: 2 }, { t: "CHARLIE", o: 0, x: 1, y: 4 },
      { t: "PANTHER", o: 0, x: 2, y: 3 }, { t: "BISON", o: 0, x: 1, y: 3 },
      { t: "EAGLE", o: 0, x: 2, y: 4 },
      { t: "CHARLIE", o: 1, x: 13, y: 2 }, { t: "CHARLIE", o: 1, x: 13, y: 4 },
      { t: "PANTHER", o: 1, x: 12, y: 3 }, { t: "GRIZZLY", o: 1, x: 13, y: 3 },
      { t: "EAGLE", o: 1, x: 12, y: 4 },
    ] },

  { name: "HALLEY", blurb: "Air superiority decides this one. Falcons hunt fighters, Hawkeyes deny airspace, and the ground war waits on the winner.",
    turnLimit: 45,
    grid: [
      "vvvv........vvvv",
      "vv............vv",
      "....hh....hh....",
      "................",
      "B......vv......B",
      "................",
      "....hh....hh....",
      ".F............F.",
      "vv............vv",
      "vvvv........vvvv",
    ],
    buildings: [
      { col: 0, row: 4, owner: 0 },
      { col: 15, row: 4, owner: 1 },
      { col: 1, row: 7, owner: 0, stored: ["HUNTER"] },
      { col: 14, row: 7, owner: 1, stored: ["HUNTER"] },
    ],
    units: [
      { t: "EAGLE", o: 0, x: 1, y: 3 }, { t: "FALCON", o: 0, x: 2, y: 4 },
      { t: "HUNTER", o: 0, x: 2, y: 5 }, { t: "SEEKER", o: 0, x: 1, y: 5 },
      { t: "HAWKEYE", o: 0, x: 2, y: 6 }, { t: "BISON", o: 0, x: 1, y: 4 },
      { t: "CHARLIE", o: 0, x: 2, y: 3 },
      { t: "EAGLE", o: 1, x: 14, y: 3 }, { t: "FALCON", o: 1, x: 13, y: 4 },
      { t: "HUNTER", o: 1, x: 13, y: 5 }, { t: "SEEKER", o: 1, x: 14, y: 5 },
      { t: "HAWKEYE", o: 1, x: 13, y: 6 }, { t: "GRIZZLY", o: 1, x: 14, y: 4 },
      { t: "CHARLIE", o: 1, x: 13, y: 3 },
    ] },

  { name: "BORMAN", blurb: "A mountain-walled fortress with one mined gate, an Atlas inside, and your own Atlas crated in a rear factory.",
    turnLimit: 50,
    grid: [
      "................",
      "....ww....MMMM..",
      "..........M.BM..",
      "..........MM.M..",
      "......hh........",
      "B---............",
      "......ww........",
      "....hh..........",
      "................",
      "..F.............",
      "................",
    ],
    buildings: [
      { col: 0, row: 5, owner: 0 },
      { col: 12, row: 2, owner: 1 },
      { col: 2, row: 9, owner: 0, stored: ["ATLAS"] },
    ],
    units: [
      { t: "BISON", o: 0, x: 1, y: 4 }, { t: "POLAR", o: 0, x: 2, y: 5 },
      { t: "TITAN", o: 0, x: 2, y: 4 }, { t: "HADRIAN", o: 0, x: 1, y: 6 },
      { t: "CHARLIE", o: 0, x: 2, y: 6 }, { t: "KILROY", o: 0, x: 1, y: 5 },
      { t: "EAGLE", o: 0, x: 3, y: 5 }, { t: "PELICAN", o: 0, x: 2, y: 7 },
      { t: "MULE", o: 0, x: 3, y: 6 },
      { t: "TRIGGER", o: 1, x: 12, y: 3 }, { t: "ATLAS", o: 1, x: 11, y: 2 },
      { t: "KILROY", o: 1, x: 12, y: 2 }, { t: "GRIZZLY", o: 1, x: 11, y: 4 },
      { t: "POLAR", o: 1, x: 12, y: 5 }, { t: "OCTOPUS", o: 1, x: 13, y: 5 },
      { t: "HAWKEYE", o: 1, x: 12, y: 6 }, { t: "CHARLIE", o: 1, x: 13, y: 4 },
      { t: "FALCON", o: 1, x: 13, y: 6 },
    ] },

  { name: "LOVELL", blurb: "A wide front with valley teeth. Four flank factories reward whoever splits their force well.",
    turnLimit: 50,
    grid: [
      "hh.....vvv.....hh",
      ".................",
      "..F....vvv....F..",
      ".................",
      "....hh.....hh....",
      "B.......w.......B",
      "....hh.....hh....",
      ".................",
      "..F....vvv....F..",
      ".................",
      "hh.....vvv.....hh",
    ],
    buildings: [
      { col: 0, row: 5, owner: 0 },
      { col: 16, row: 5, owner: 1 },
      { col: 2, row: 2, owner: 0, stored: ["RABBIT"] },
      { col: 14, row: 2, owner: 1, stored: ["LYNX"] },
      { col: 2, row: 8, owner: 0, stored: ["LENET"] },
      { col: 14, row: 8, owner: 1, stored: ["BISON"] },
    ],
    units: [
      { t: "BISON", o: 0, x: 1, y: 4 }, { t: "LENET", o: 0, x: 1, y: 6 },
      { t: "POLAR", o: 0, x: 2, y: 5 }, { t: "TITAN", o: 0, x: 3, y: 5 },
      { t: "HADRIAN", o: 0, x: 2, y: 4 }, { t: "CHARLIE", o: 0, x: 2, y: 6 },
      { t: "PANTHER", o: 0, x: 3, y: 4 }, { t: "EAGLE", o: 0, x: 3, y: 6 },
      { t: "SEEKER", o: 0, x: 1, y: 5 },
      { t: "GRIZZLY", o: 1, x: 15, y: 4 }, { t: "TITAN", o: 1, x: 15, y: 6 },
      { t: "POLAR", o: 1, x: 14, y: 5 }, { t: "SLAGGER", o: 1, x: 13, y: 5 },
      { t: "OCTOPUS", o: 1, x: 14, y: 6 }, { t: "CHARLIE", o: 1, x: 14, y: 4 },
      { t: "PANTHER", o: 1, x: 13, y: 6 }, { t: "FALCON", o: 1, x: 13, y: 4 },
      { t: "HAWKEYE", o: 1, x: 15, y: 5 },
    ] },

  { name: "IRWIN", blurb: "Shattered ground: valleys carve the map into islands. Infantry, wings and airlifts rule; a Giant waits in the middle.",
    turnLimit: 50,
    grid: [
      "..vv.....vv......",
      "......vv.....vv..",
      "..MM.......MM....",
      ".vv...hh....vv...",
      "........F........",
      "B...vv....vv....B",
      ".................",
      "...vv...hh...vv..",
      "....MM.....MM....",
      "..vv.....vv......",
      ".....vv......vv..",
    ],
    buildings: [
      { col: 0, row: 5, owner: 0 },
      { col: 16, row: 5, owner: 1 },
      { col: 8, row: 4, owner: -1, stored: ["GIANT"] },
    ],
    units: [
      { t: "KILROY", o: 0, x: 1, y: 4 }, { t: "CHARLIE", o: 0, x: 1, y: 6 },
      { t: "PANTHER", o: 0, x: 2, y: 5 }, { t: "EAGLE", o: 0, x: 2, y: 4 },
      { t: "HUNTER", o: 0, x: 2, y: 6 }, { t: "LENET", o: 0, x: 3, y: 5 },
      { t: "PELICAN", o: 0, x: 1, y: 5 },
      { t: "KILROY", o: 1, x: 15, y: 4 }, { t: "CHARLIE", o: 1, x: 15, y: 6 },
      { t: "PANTHER", o: 1, x: 14, y: 5 }, { t: "EAGLE", o: 1, x: 14, y: 4 },
      { t: "HUNTER", o: 1, x: 14, y: 6 }, { t: "GRIZZLY", o: 1, x: 13, y: 5 },
      { t: "PELICAN", o: 1, x: 15, y: 5 },
    ] },

  { name: "NECTARIS", blurb: "The last stand: every unit type, four factories, and a fortified enemy line. Take their base.",
    turnLimit: 50,
    grid: [
      "MMhh..........hhMM",
      "M................M",
      "..F....vv.....F...",
      ".....ww....ww.....",
      "...hh........hh...",
      "B-------..-------B",
      "...hh........hh...",
      ".....ww....ww.....",
      "..F....vv.....F...",
      "M................M",
      "MMhh..........hhMM",
      "..................",
    ],
    buildings: [
      { col: 0, row: 5, owner: 0 },
      { col: 17, row: 5, owner: 1 },
      { col: 2, row: 2, owner: 0, stored: ["HUNTER"] },
      { col: 2, row: 8, owner: 0, stored: ["GIANT"] },
      { col: 14, row: 2, owner: 1, stored: ["HUNTER"] },
      { col: 14, row: 8, owner: 1, stored: ["ATLAS", "TRIGGER"] },
    ],
    units: [
      { t: "BISON", o: 0, x: 1, y: 4 }, { t: "BISON", o: 0, x: 1, y: 6 },
      { t: "POLAR", o: 0, x: 2, y: 5 }, { t: "TITAN", o: 0, x: 2, y: 4 },
      { t: "SLAGGER", o: 0, x: 3, y: 5 }, { t: "HADRIAN", o: 0, x: 1, y: 5 },
      { t: "CHARLIE", o: 0, x: 2, y: 6 }, { t: "KILROY", o: 0, x: 1, y: 3 },
      { t: "PANTHER", o: 0, x: 2, y: 7 }, { t: "EAGLE", o: 0, x: 3, y: 4 },
      { t: "FALCON", o: 0, x: 2, y: 3 }, { t: "SEEKER", o: 0, x: 3, y: 3 },
      { t: "MULE", o: 0, x: 2, y: 9 }, { t: "PELICAN", o: 0, x: 1, y: 7 },
      { t: "GRIZZLY", o: 1, x: 16, y: 4 }, { t: "GRIZZLY", o: 1, x: 16, y: 6 },
      { t: "POLAR", o: 1, x: 15, y: 5 }, { t: "TITAN", o: 1, x: 15, y: 4 },
      { t: "SLAGGER", o: 1, x: 14, y: 5 }, { t: "OCTOPUS", o: 1, x: 16, y: 5 },
      { t: "CHARLIE", o: 1, x: 15, y: 6 }, { t: "KILROY", o: 1, x: 16, y: 3 },
      { t: "PANTHER", o: 1, x: 15, y: 7 }, { t: "EAGLE", o: 1, x: 14, y: 4 },
      { t: "FALCON", o: 1, x: 15, y: 3 }, { t: "HAWKEYE", o: 1, x: 14, y: 6 },
      { t: "SEEKER", o: 1, x: 14, y: 3 }, { t: "TRIGGER", o: 1, x: 15, y: 2 },
    ] },
];

if (typeof module !== "undefined") module.exports = CAMPAIGN;
