'use strict';
// Names, silhouettes and tactical readings were assigned AFTER analyze.js selected the numbers.
module.exports = [
  {id:'BASTION', name:'Bastion SP-82', cls:'artillery', role:'Fixed dual-domain missile nest',
    gap:'No original stationary unit can attack aircraft. Neither target domain has a stationary, exact-two-hex weapon.',
    use:'Place one hex behind a contested front. Its ground attack of 50 and air attack of 85 cover the second ring while its 60 defense helps it survive bombardment. Both weapons fire at exactly two hexes.',
    trade:'Cannot move after deployment or shoot adjacent enemies. A ground screen is essential; enemies that get alongside it receive no counterfire.',
    experiment:'Test whether 85 air attack and 60 defense make a protected second-ring nest too difficult to remove.',
    art:'Four braced feet, a low armored roof and two outward missile rails.'},
  {id:'HYDRA', name:'Hydra MR-90', cls:'artillery', role:'Creeping dual-domain assault launcher',
    gap:'No original unit has indirect weapons against both domains, and none uses a ground band of 2–3.',
    use:'Shift one plains or road hex and fire at ground or air targets two to three hexes away. It combines Atlas-level ground attack with Hawkeye-level air attack, but needs no setup turn.',
    trade:'Only 10 defense and one movement point. It cannot normally climb a hill in one activation, and neither weapon covers the adjacent ring. Losing its screen is usually fatal.',
    experiment:'Test the very high firepower first. The screening budget is a design constraint, not evidence this damage is balanced.',
    art:'An exposed staggered missile rack on a tiny, lightly armored crawler.'},
  {id:'TORTOISE', name:'Tortoise AS-80', cls:'antiair', role:'Fast armored screening battery',
    gap:'The stock roster never combines 80 defense with fast movement; all stock indirect batteries have 30 defense or less.',
    use:'Shift up to eight plains hexes to occupy a blocking position. On a later turn, engage ground targets at 2–3 hexes or aircraft at exactly two. Defense and repositioning are its primary assets.',
    trade:'Moving sacrifices its shot. Ground attack is only 10 and air attack 40; it cannot counter an adjacent assault. High defense benefits strongly from terrain.',
    experiment:'Check 80 defense plus terrain and defensive support: the combat defense cap may make this too reliable as a roadblock.',
    art:'Long slab skirts, a low casemate and a recessed upward missile slot.'},
  {id:'WATCHMAN', name:'Watchman AD-24', cls:'antiair', role:'Light deployable air-defense post',
    gap:'Air range 2–4 and stationary anti-air duty are both absent from the original roster.',
    use:'Protect a staging area against aircraft at two to four hexes. Its small adjacent ground gun can counter ground attackers and contribute in adjacent ground exchanges.',
    trade:'Cannot relocate under its own power. Defense 20 and ground attack 10 mean a tank can dismantle it; aircraft at distance one cannot be engaged.',
    experiment:'Compare its transport and deployment effort with simply moving a Hawkeye into position.',
    art:'A tall rectangular radar vane, twin missiles and a small ground-defense barrel.'},
  {id:'MARTEN', name:'Marten MX-85', cls:'infantry', role:'Capturing anti-air missile sidecar',
    gap:'No stock capturer has indirect fire or post-attack movement. Air range exactly two is also unoccupied.',
    use:'Travel on roads, fire a strong anti-air shot from two hexes, then spend any remaining movement to withdraw. It can also capture factories and the enemy base.',
    trade:'Wheels pay two points per plains hex and four per hill. It cannot enter waste, mountains or valleys; defense is 10 and its ground attack is only 10. Neither weapon shoots adjacent targets.',
    experiment:'Check whether combining capture, 85 air attack and retreat leaves enough room for the existing Panther and Hawkeye.',
    art:'A small rider, long sidecar missile rail and three exposed wheels.'},
  {id:'MIDGE', name:'Midge GX-12', cls:'infantry', role:'Portable anti-air harassment team',
    gap:'All original foot units capture and use direct fire. There is no foot unit with an indirect shot and a retreat phase.',
    use:'Move through hills or onto a mountain approach, attack an aircraft exactly two hexes away, then use remaining movement to step back. It is a terrain-access and tempo experiment.',
    trade:'Air attack is only 10, defense 10, no ground weapon and no capture ability. Its niche may be numerically unusual but too weak to justify a scenario slot.',
    experiment:'Lowest-priority balance candidate: verify that repeat harassment ever matters without relying on a price discount; this game has no purchase economy.',
    art:'A small crouched operator and a slim shoulder missile, with an open lower silhouette.'},
  {id:'GORGON', name:'Gorgon SG-80', cls:'artillery', role:'Armored close barrage / distant air cover',
    gap:'No original battery splits ground fire at exactly two hexes from long-range anti-air fire.',
    use:'Hold a prepared position. Ground attack 80 threatens the second ring while weaker air attack 30 reaches aircraft two to five hexes away. Defense 60 supports a durable firing line.',
    trade:'One movement point and move-or-fire make redeployment slow. Both weapons have an adjacent blind spot; long air reach comes with modest damage.',
    experiment:'Check how a protected 80-power second-ring gun compares with Octopus after accounting for the narrower ground band.',
    art:'A deep armored carriage, short heavy mortar and high rear missile mast.'},
  {id:'BADGER', name:'Badger CBX-8', cls:'infantry', role:'Slow armored-breaching capture team',
    gap:'The capturer set stops at 40 ground attack. None combines direct ground attack with an exact-two air weapon and setup restriction.',
    use:'Stage on a road beside a defended objective. Its adjacent ground weapon hits at 80; once a path is open, it can move onto a factory or the enemy base.',
    trade:'Only one wheeled movement point: it cannot normally traverse plains or hills in a single activation. Moving prevents firing; defense 10 makes road confinement dangerous. Pelican delivery helps.',
    experiment:'A deliberately severe mobility trade. Test on road-connected objectives before considering any speed adjustment.',
    art:'A small operator behind a wheeled breech shield with a short cannon and rear missile.'},
  {id:'RAMPART', name:'Rampart HV-90', cls:'tank', role:'Rapid armored obstruction',
    gap:'Trigger supplies high-defense obstruction without movement. No stock unit gives up its ground weapon for very fast, 80-defense ground blocking.',
    use:'Use nine tracked movement points to close a lane, establish ZOC or stand beside a friendly defender to contribute defense support. It has a token adjacent anti-air gun.',
    trade:'Cannot attack or counter ground targets, cannot capture and carries nothing. Surround can cut its defenses; repeated air shots do little damage.',
    experiment:'Defense 80 reaches the cap on hills before surround is applied. Test blockage duration and supported fights, not only its zero ground damage.',
    art:'A turretless armored wedge with broad side shields and one tiny anti-air stub.'},
  {id:'HORNET', name:'Hornet GX-43', cls:'infantry', role:'All-terrain mixed missile team',
    gap:'There is no non-capturing foot battery, no foot defense above 10 and no original air band of 2–3.',
    use:'Cross hills or mountain approaches with foot costs, then fire during the same turn. It engages ground targets at exactly two hexes and aircraft at two to three.',
    trade:'Ground attack is only 10. Its 30 defense is strong for foot troops, but it cannot capture, retreat after firing or counter at distance one.',
    experiment:'Check mountain defense and same-turn repositioning against Hawkeye; its shorter air reach should remain a meaningful weakness.',
    art:'A small infantry figure with a broad rectangular missile pack and separate sight.'},
  {id:'ANVIL', name:'Anvil SG-32', cls:'artillery', role:'Durable deployable field gun',
    gap:'The original stationary ground gun has high attack and low defense. The middle-power, armored position is empty, as is its adjacent air-defense combination.',
    use:'Deploy an enduring ground battery with attack 30 at two to four hexes. An adjacent air weapon at 20 discourages aircraft from exploiting the ground gun’s blind spot.',
    trade:'No self-propelled movement; ground attackers alongside it receive no counterfire. Its lower damage trades immediate casualties for position-holding.',
    experiment:'Measure whether 50 defense is worth a transport activation compared with Atlas’s much stronger bombardment.',
    art:'A wide split trail, thick central shield, elevated gun and small side anti-air tube.'},
  {id:'BASILISK', name:'Basilisk AG-85', cls:'artillery', role:'Heavy artillery with point air defense',
    gap:'No stock unit combines long ground bombardment, very strong adjacent anti-air and heavy armor.',
    use:'Fire at ground targets two to five hexes away. Aircraft closing to attack at distance one face an 85-power counterweapon, while defense 70 protects the battery.',
    trade:'Only one tracked movement point and move-or-fire. It cannot attack aircraft farther away or shoot an adjacent ground attacker. Slow relocation makes placement decisive.',
    experiment:'Heavy armor plus powerful air counters may overprotect a battery; compare ground-rush and indirect-fire counters in playtests.',
    art:'A deep tracked hull with a long gun and a visibly separate twin upward anti-air mount.'},
  {id:'LANCER', name:'Lancer GX-73', cls:'infantry', role:'Foot anti-air guard with light mortar',
    gap:'Original foot anti-air attack is fixed at 10. None trades capture for powerful direct air defense and indirect ground fire.',
    use:'Walk into a hill or mountain position, then hold it. Air attack 70 counters adjacent aircraft, while a light ground mortar can reach two to three hexes.',
    trade:'Move or fire, two movement points, defense 10 and no capture. Ground attack 10 is support harassment rather than a tank killer; adjacent ground enemies are safe from its gun.',
    experiment:'Test whether terrain access compensates for being much less mobile and less armored than Seeker.',
    art:'A small kneeling gunner, long upward launcher and compact mortar footplate.'},
  {id:'STOAT', name:'Stoat GX-80', cls:'infantry', role:'Capturing ambush missile team',
    gap:'No original capturer attacks indirectly or retreats after firing; foot ground attack never exceeds 40.',
    use:'Advance through hills, hit a ground target exactly two hexes away at attack 80, then spend remaining movement to withdraw. It can also seize buildings on later activations.',
    trade:'Defense 10 and no air weapon. It cannot attack or counter an adjacent tank. Firing does not refill its four movement points; ZOC can prevent the planned escape.',
    experiment:'The capture and retreat combination is a major new tactical privilege. Test whether the two-hex blind spot sufficiently limits it.',
    art:'A low running operator with a long horizontal anti-tank missile and small backpack.'},
  {id:'KESTREL', name:'Kestrel MM-93', cls:'artillery', role:'Rapid redeployment missile battery',
    gap:'Stock move-or-fire batteries have four or five movement points and single-domain fire. None has nine-point repositioning and two indirect bands.',
    use:'Move rapidly between firing positions, then on a subsequent turn bombard ground targets at two to five hexes or aircraft at two to three. Air attack 60 is its stronger weapon.',
    trade:'Defense 10 makes this a fragile battery, and moving sacrifices all fire that turn. Both weapons are helpless against adjacent targets.',
    experiment:'Check whether rapid redeployment creates useful choices despite the lost firing turn, especially on small maps.',
    art:'A long low crawler with a forward cab, sloped missile bank and tall rear radar fin.'}
];
