#!/usr/bin/env python3
"""Embed the thanks page's photographs and write their credits.

The hosted site accepts only css/html/js/json/md files and its
Content-Security-Policy allows images from 'self' and data: only, so each
picture ships inside css/thanks-images.css as a WebP data URL. Every file comes
from Wikimedia Commons under a free license; anything else is refused. The
picture-credit list in thanks.html is regenerated between its markers.

    python3 tools/build-thanks-images.py
"""
import base64
import html
import io
import json
import re
import urllib.parse
import urllib.request
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
CSS = ROOT / "css" / "thanks-images.css"
PAGE = ROOT / "thanks.html"
API = "https://commons.wikimedia.org/w/api.php"
HEADERS = {"User-Agent": "nectaris-remake-thanks-page/1.0 (https://github.com/ernop/nectaris-remake)"}
FREE_LICENSE = re.compile(r"^(Public domain|CC0|CC BY(-SA)? \d\.\d)$")
BEGIN = "<!-- BEGIN picture credits: generated by tools/build-thanks-images.py -->"
END = "<!-- END picture credits -->"

# (CSS class suffix, Commons file, width to fetch in pixels)
PHOTOS = [
    ("moon", "File:Montes Pyrenaeus meets Mare Nectaris (LROC31 - NearsideNectarisHighlight).png", 900),
    ("hudson", "File:ハドソン札幌本社２.jpg", 300),
    ("pce", "File:PC-Engine-Console-Set.jpg", 640),
    ("tg16", "File:TurboGrafx16-Console-Set.jpg", 640),
    ("pc98", "File:PC-9801 computer set.jpg", 560),
    ("x68k", "File:X68000ACE-HD.JPG", 360),
    ("scd", "File:Super CD-ROM2 with CoreGrafx II (3-4 left view).jpg", 560),
    ("huelsbeck", "File:Chris Huelsbeck NextLevel 2 2011 Köln (cropped).jpg", 420),
    ("gameboy", "File:Game-Boy-FL.jpg", 420),
    ("psx", "File:PSX-Console-wController.jpg", 640),
    ("xbox360", "File:Microsoft-Xbox-360-Pro-Flat-wController-L.jpg", 640),
]


def fetch(url):
    with urllib.request.urlopen(urllib.request.Request(url, headers=HEADERS), timeout=60) as response:
        return response.read()


def image_info(title, width):
    query = urllib.parse.urlencode({
        "action": "query", "titles": title, "prop": "imageinfo", "format": "json",
        "formatversion": "2", "iiprop": "url|extmetadata", "iiurlwidth": str(width)})
    page = json.loads(fetch(f"{API}?{query}"))["query"]["pages"][0]
    if "imageinfo" not in page:
        raise ValueError(f"Commons has no file named {title}")
    info = page["imageinfo"][0]
    meta = info["extmetadata"]
    license_name = meta["LicenseShortName"]["value"]
    if not FREE_LICENSE.match(license_name):
        raise ValueError(f"{title} is not freely licensed: {license_name}")
    artist = html.unescape(re.sub(r"<[^>]+>", "", meta["Artist"]["value"])).strip()
    return {"thumb": info["thumburl"], "page": info["descriptionurl"],
            "license": license_name, "artist": " ".join(artist.split())}


def webp_data_url(data, width):
    picture = Image.open(io.BytesIO(data))
    picture = picture.convert("RGBA" if "A" in picture.getbands() else "RGB")
    if picture.width > width:
        picture = picture.resize((width, round(picture.height * width / picture.width)), Image.LANCZOS)
    out = io.BytesIO()
    picture.save(out, "WEBP", quality=80, method=6)
    return picture.size, "data:image/webp;base64," + base64.b64encode(out.getvalue()).decode()


def main():
    rules, credits = [], []
    for key, title, width in PHOTOS:
        info = image_info(title, width)
        (w, h), url = webp_data_url(fetch(info["thumb"]), width)
        rules.append(f'.photo-{key} {{ aspect-ratio: {w} / {h}; background-image: url("{url}"); }}')
        name = html.escape(title.removeprefix("File:"))
        credits.append(f'<li><a href="{html.escape(info["page"])}">{name}</a>: '
                       f'{html.escape(info["artist"])}, {html.escape(info["license"])}</li>')
        print(f"{key}: {w}x{h}, {len(url) // 1024} KiB, {info['license']}, {info['artist']}")
    CSS.write_text("/* Generated by tools/build-thanks-images.py from Wikimedia Commons."
                   " Credits are listed on thanks.html. */\n" + "\n".join(rules) + "\n")
    page = PAGE.read_text()
    start, stop = page.index(BEGIN) + len(BEGIN), page.index(END)
    PAGE.write_text(page[:start] + "\n<ul class=\"picture-credits\">\n" + "\n".join(credits)
                    + "\n</ul>\n" + page[stop:])
    print(f"wrote {CSS.relative_to(ROOT)} ({CSS.stat().st_size // 1024} KiB) and the credits in thanks.html")


if __name__ == "__main__":
    main()
